// <auto-generated />
using gestionAdminTECOCApi.Infrastructure.PostgreSql.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using System;

#nullable disable

namespace gestionAdminTECOCApi.Infrastructure.PostgreSql.Migrations;
[DbContext( typeof( ApplicationDbContext ) )]
[Migration( "20260823151711_v1-0-1" )]
partial class v101 {
    /// <inheritdoc />
    protected override void BuildTargetModel( ModelBuilder modelBuilder ) {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema( "gestionAdminTECOCApiMS" )
            .HasAnnotation( "ProductVersion", "7.0.18" )
            .HasAnnotation( "Relational:MaxIdentifierLength", 63 );

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns( modelBuilder );

        modelBuilder.Entity( "gestionAdminTECOCApi.Domain.Users.User", b => {
            b.Property<Guid>( "Id" )
                .ValueGeneratedOnAdd()
                .HasColumnType( "uuid" );

            b.Property<string>( "DocumentNumber" )
                .IsRequired()
                .HasMaxLength( 15 )
                .HasColumnType( "character varying(15)" );

            b.Property<string>( "DocumentType" )
                .IsRequired()
                .HasMaxLength( 40 )
                .HasColumnType( "character varying(40)" );

            b.Property<bool>( "Enabled" )
                .HasColumnType( "boolean" );

            b.Property<string>( "FullName" )
                .IsRequired()
                .HasMaxLength( 150 )
                .HasColumnType( "character varying(150)" );

            b.Property<string>( "Position" )
                .IsRequired()
                .HasMaxLength( 100 )
                .HasColumnType( "character varying(100)" );

            b.HasKey( "Id" );

            b.HasIndex( "DocumentType", "DocumentNumber" )
                .IsUnique();

            b.ToTable( "Users", "gestionAdminTECOCApiMS" );
        } );

        modelBuilder.Entity( "gestionAdminTECOCApi.Domain.WeatherForecasts.WeatherForecast", b => {
            b.Property<Guid>( "Id" )
                .ValueGeneratedOnAdd()
                .HasColumnType( "uuid" );

            b.Property<DateOnly>( "Date" )
                .HasColumnType( "date" );

            b.Property<bool>( "Enabled" )
                .HasColumnType( "boolean" );

            b.Property<string>( "Summary" )
                .HasColumnType( "text" );

            b.Property<int>( "Temperature" )
                .HasColumnType( "integer" );

            b.Property<int>( "TemperatureC" )
                .HasColumnType( "integer" );

            b.HasKey( "Id" );

            b.ToTable( "WeatherForecasts", "gestionAdminTECOCApiMS" );
        } );

        modelBuilder.Entity( "gestionAdminTECOCApi.Domain.WeatherForecastsHistories.WeatherForecastsHistory", b => {
            b.Property<Guid>( "Id" )
                .ValueGeneratedOnAdd()
                .HasColumnType( "uuid" );

            b.Property<string>( "CreatedByUser" )
                .HasColumnType( "text" );

            b.Property<DateOnly?>( "CreatedDate" )
                .HasColumnType( "date" );

            b.Property<bool>( "Enabled" )
                .HasColumnType( "boolean" );

            b.Property<string>( "LastModifiedByUser" )
                .HasColumnType( "text" );

            b.Property<DateOnly?>( "LastModifiedDate" )
                .HasColumnType( "date" );

            b.Property<string>( "Proccess" )
                .HasColumnType( "text" );

            b.HasKey( "Id" );

            b.ToTable( "WeatherForecastsHistories", "gestionAdminTECOCApiMS" );
        } );
#pragma warning restore 612, 618
    }
}
